### ISSUE TITLE
Link to this repo from home page of jenkins.dataverse.org

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse-jenkins#14]
I'd like to have something like "For more information about this server: https://github.com/IQSS/dataverse-jenkins " on the home page https://jenkins.dataverse.org such as in the mockup below.

<img width="1552" alt="Screen Shot 2019-08-30 at 5 35 59 AM" src="https://user-images.githubusercontent.com/21006/64010618-21373380-cae8-11e9-8f3b-432e3abf747f.png">

That way, people visiting can discover this repo, contribute, and perhaps find the configs and run their own version of Jenkins to build Dataverse and related projects (#1).

We should, of course, capture this config in this repo.

**Comment by donsizemore** [comment]
I enabled "safe HTML" markup, and added a link in Jenkins' description field in the header.

**Comment by pdurbin** [comment]
@donsizemore looks great! Thank you!!
