### ISSUE TITLE
jenkins should generate test results page

### ISSUE THREAD

**Issue by donsizemore** [IQSS/dataverse-jenkins#4]
![test_results](https://user-images.githubusercontent.com/12831666/57326210-f7da3e00-70d9-11e9-8411-458b6d50ed46.png)

**Comment by donsizemore** [comment]
is this the right page? https://jenkins.dataverse.org/job/IQSS-dataverse-develop/lastBuild/testReport/

**Comment by pdurbin** [comment]
@donsizemore no, those are the unit tests. They run as part of `mvn package` when you build the war file. I'm talking about the API test suite, which requires a running Glassfish, Postgres, and Solr. Should this issue be in dataverse-jenkins?

**Comment by donsizemore** [comment]
these are being dumped into site/ at the end of each run.
